export const Types = {
    'call-end': 'Call end',
    'call-start': 'Call start',  
    'call-attempt': 'Call attempt',
    'alert': 'Alert',
    'error': 'Error',
    'recording': 'Recording',
    'message-log': 'Message log',
    'limit': 'Limit',
    'prompt': 'Prompt',
    'message-dropped': 'Message dropped',
    'action-log': 'Action log',
    'reg-new': 'Reg new',
    'reg-del': 'Reg del',
    'reg-expired': 'Reg expired',
    'auth-failed': 'Auth failed',
    'notice': 'Notice',
    'log-reply': 'Log reply',  
    'fbl-new': 'Firewall blacklist',
    'fgl-new': 'Firewall greylist',
    'conf-leave': 'Conference leave',
    'conf-join': 'Conference join',
    'conference_room': 'Conference room',
    "other-failed": 'Other failed',
    "other-timeout": 'Other timeout',
    "other-ok": 'Other ok',
    "parse-error": 'Parse error',
    "msg-probe": 'Msg probe',
    "low_MoS": "Low MoS",
    "high_rx": "High RX",
    "high_tx": "High TX",
    "call_start": "Call start",
    "honeynet": "Honeynet",
    "short_calls_ip": "Short calls IP",
    "short_calls_uri": "Short calls URI",
    "limit_ip": "Limit",
    "drop_ip": "Drop",
    "authfail_ip" : "Auth-failed IP",
    "authfail_uri": "Auth-failed URI",
    "ip_limit_behind_uri": "IPs behind URI",
    "uri_limit_behind_ip": "URIs behind IP",
    "changing_location": "Diff country",
    "too_many_minutes": "Too many minutes",
    "poor_ratio_ca": "Poor ratio CA",
    "CA_unreachable": "CA unreachable",
    "poor_parallel_reg": "Poor parallel reg",
    "security_metrics": "Security metrics"
}
    
export default Types;