
export const SET_TIMERANGE_GTE = "SET_TIMERANGE_GTE";
export const SET_TIMERANGE_LTE = "SET_TIMERANGE_LTE";
export const SET_TIMERANGE = "SET_TIMERANGE";
export const ASSIGN_TYPE = "ASSIGN_TYPE";
export const SET_FILTERS = "SET_FILTERS";
export const SET_USER = "SET_USER";
export const SET_WIDTH_CHART = "SET_WIDTH_CHART";
export const SET_PROFILE = "SET_PROFILE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";

